### ISSUE TITLE
Getting Started !

### ISSUE THREAD

**Issue by underwater** [weblinq/WebLinq#14]
Just getting started, and using NuGet to download alpha of WebLinq and using an example from the project, and noticed the type IQuery<T> and the .Content() method from SeqQuery aren't being recognized.    

errors are

- The type or namespace name 'IQuery<>' could not be found (are you missing a using directive or an assembly reference?)	
-  'SeqQuery<HtmlObject>' does not contain a definition for 'Content' and no extension method 'Content' accepting a first argument of type 'SeqQuery<HtmlObject>' could be found (are you missing a using directive or an assembly reference?)

Any ideas what I can be doing wrong ?  Downloading the library itself and running the samples works fine.
Thanks

**Comment by atifaziz** [comment]
The problem is that NuGet had an older version from July (1.0.0-alpha-20160712T1550). The [MyGet feed has the latest builds as code is pushed out to the repo](https://www.myget.org/feed/raboof/package/nuget/WebLinq). I've just pushed the [latest one (1.0.0-alpha-20161114T0545)](https://www.myget.org/feed/raboof/package/nuget/WebLinq/1.0.0-alpha-20161114T0545) to NuGet & it should take care of those errors. If it does, please close the issue otherwise let me know if you're still having trouble.

**Comment by underwater** [comment]
Thank you, this in fact resolved the issue ;-)   Looking forward to discover this really nice library
